"""empty message

Revision ID: 44cfe4b51d53
Revises: 76a2ee8bb141
Create Date: 2017-09-07 22:07:13.475394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44cfe4b51d53'
down_revision = '76a2ee8bb141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('first_sms', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'first_sms')
    # ### end Alembic commands ###
